branches:
  only:
    - $env.source_branch

build_script:
  - ps: "Install-Product node 8 x64"
  - yarn install
  - npm run build

environment:
  source_branch: develop

image: Visual Studio 2017

on_success:
# Setup git configuration then push the built files to the gh-pages branch.
  - xcopy ".git" "..\temp\.git\" /E
  - xcopy dist ..\temp\ /E
  - ps: Remove-Item * -Recurse -Force
  - xcopy ..\temp .\ /E /H /Y
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "%APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL%"
  - git config --global user.name "%APPVEYOR_REPO_COMMIT_AUTHOR%"
  - git checkout -b gh-pages
  - git add .
  - git commit -m "AppVeyor build - branch=%APPVEYOR_REPO_BRANCH%, commit=%APPVEYOR_REPO_COMMIT%" -a
  - git push -f origin gh-pages

test: off

version: 1.0.{build}
