[Settings]

[build]
  command = "sed -i \"s|MAPBOX_REDIRECT_ACCESS_TOKEN|${MAPBOX_ACCESS_TOKEN}|g\" netlify.toml && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "10.6"

[context.production]
  command = "npm run prod"

[[redirects]]
  from = "/api-mapbox"
  to = "https://api.mapbox.com/styles/v1/mapbox/outdoors-v11"
  query = {access_token = MAPBOX_REDIRECT_ACCESS_TOKEN}
  status = 200


[[redirects]]
  from = "/api/*"
  to = "http://islandexplorertracker.availtec.com/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
