[Settings]

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "10.6"

[context.develop.environment]
  command = "ECHO Develop Environment"
  NODE_ENV = "development"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
