[Settings]

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "10.6"

[context.production]
  command = "npm run prod"

[[redirects]]
  from = "/api/*"
  to = "http://islandexplorertracker.availtec.com/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
